---
title: "440 Case Study I"
author: "Jake Epstein, Daniel Spottiswood, Michael Tan, Sahil Patel, Man-Lin Hsiao"
date: "9/3/2019"
output: html_document
---

## Set Up, Load, Clean Data
```{r}
## load packages
library(dplyr)

## read in data
births = read.csv("data/Yr1116Birth.csv", na.strings = "9999")
deaths = read.csv("data/Yr1116Death.csv")

## rewrite NAs
births$SEX[which(births$SEX == 9)] = NA
births$CIGPN[which(births$CIGPN == 99)] = NA
births$CIGFN[which(births$CIGFN == 99)] = NA
births$CIGSN[which(births$CIGSN == 99)] = NA
births$CIGLN[which(births$CIGLN == 99)] = NA
births$PARITY[which(births$PARITY == 99)] = NA
births$GEST[which(births$GEST == 99)] = NA
births$MAGE[which(births$MAGE == 99)] = NA
```


## Exploratory Data Analysis

### Birthweight

### Smoking

### Parity

### Plurality

### Gestation

### Age of Mother

### Race of Mother

### County / Socioeconomic Status
```{r}
#calculate infant mortality by county
deaths_by_county = deaths %>%
  # filter(!is.na(cores)) %>%
  group_by(cores) %>%
  summarize(n_deaths = n()) %>%
  rename(CORES=cores)

births_by_county = births %>%
  # filter(!is.na(CORES)) %>%
  group_by(CORES) %>%
  summarize(n_births = n())

infant_mortality = merge(deaths_by_county, births_by_county, by = "CORES") %>%
  mutate(mortality = n_deaths/n_births) %>%
  select(-n_births, -n_deaths)

birth = merge(births, infant_mortality, by = "CORES")


```
